FROM centos:8

RUN \
    dnf install -y epel-release && \
    # os update 및 httpd 설치
    dnf update -y && dnf install -y httpd && \
    dnf install -y passwd sudo ncurses wget && \
    mkdir /setup && \
    # tomcat, jdk 다운로드
    wget -O /setup/tomcat.tgz http://mirror.navercorp.com/apache/tomcat/tomcat-9/v9.0.35/bin/apache-tomcat-9.0.35.tar.gz && \
    wget -O /setup/jdk-11.tgz https://download.java.net/java/GA/jdk11/9/GPL/openjdk-11.0.2_linux-x64_bin.tar.gz



